### ISSUE TITLE
Update to 1.11

### ISSUE THREAD

**Issue by JRK80** [OGRECave/ogre-assimp#5]
ogre-assimp still seems to target 1.10. When trying to compile with OGRE1.11 I get a compilation error in AssimpLoader.cpp:680, because decomposition() moved to Affine3.

I changed the line to
`Ogre::Affine3(poseTokey).decomposition(trans, scale, rot);`
which makes ogre-assimp compileable, but when trying to convert some models i get this assert:
`Assertion failed: msSingleton, file D:\OGRE\ogre-1.11.2\OgreMain\src\OgreTextureManager.cpp, line 40`
This might be a different issue, though, since I don't get the assert with every model.

**Comment by JRK80** [comment]
Tried compiling ogre-assimp with the 1.10.12 sdk. The assert vanished, so it seems to be an incompatibility with 1.11. Either that or my 1.11 compilation has some issues...

**Comment by paroj** [comment]
fixed in 47d09da06c42860e207e64897085d66bbcd618a5 and 53d8fa9c9e9c840af30bb00ecc9a4ef756fcc7e6
